const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function helper(){const ctx={fetch:async()=>({ok:true,json:async()=>({passkeys_enabled:true})}),PublicKeyCredential:function(){},isSecureContext:true};vm.runInNewContext(fs.readFileSync('assets/account-auth.js','utf8'),ctx);return ctx.SpodoraAccount}
test('internal address is never a notification email',()=>{assert.equal(helper().contactEmail({email:'random@accounts.spodora.invalid'}),'');assert.equal(helper().contactEmail({email:'real@example.com'}),'real@example.com')});
test('existing email login preserves password whitespace',async()=>{let received;const client={auth:{signInWithPassword:async x=>{received=x;return{data:{user:{id:'existing'}}}}}};await helper().login(client,' real@example.com ',' password ');assert.equal(received.email,'real@example.com');assert.equal(received.password,' password ')});
test('login ID adopts server session',async()=>{let action,adopted;const client={functions:{invoke:async(n,{body})=>{action=body;return{data:{session:{access_token:'a',refresh_token:'r'}}}}},auth:{setSession:async s=>{adopted=s;return{data:{user:{id:'new'}}}}}};await helper().login(client,'driver_123','password');assert.equal(action.action,'login');assert.equal(action.login_id,'driver_123');assert.equal(adopted.refresh_token,'r')});
test('session failure preserves the recovery code',async()=>{const client={functions:{invoke:async()=>({data:{session:{access_token:'a',refresh_token:'r'},recovery_code:'save-me'}})},auth:{setSession:async()=>({error:{}})}};await assert.rejects(helper().signup(client,'driver_123','','password',{}),e=>e.recoveryCode==='save-me')});

test('passkey login keeps the native SDK authentication',async()=>{let login=0;await helper().passkey({auth:{signInWithPasskey:async()=>{login++;return{data:{user:{id:'same'}}}}}},false);assert.equal(login,1)});
function registrationContext(info,extra={}){let shown,verified;const options={challenge:'AQI',rp:{id:'spodora.com',name:'スポドラ'},user:{id:'AwQ',name:'random@accounts.spodora.invalid',displayName:'random@accounts.spodora.invalid'},pubKeyCredParams:[{type:'public-key',alg:-7}],excludeCredentials:[{id:'BQY',type:'public-key'}],authenticatorSelection:{residentKey:'required'}};const ctx={fetch:async()=>({ok:true,json:async()=>({passkeys_enabled:true})}),PublicKeyCredential:function(){},isSecureContext:true,atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s,'binary').toString('base64'),navigator:{credentials:{create:async({publicKey})=>{shown=publicKey;return{id:'AQI',rawId:Uint8Array.from([1,2]).buffer,type:'public-key',response:{attestationObject:Uint8Array.from([7,8]).buffer,clientDataJSON:Uint8Array.from([9,10]).buffer},getClientExtensionResults:()=>({})}}}},...extra};vm.runInNewContext(fs.readFileSync('assets/account-auth.js','utf8'),ctx);const client={functions:{invoke:async()=>({data:info})},auth:{passkey:{startRegistration:async()=>({data:{challenge_id:'same-challenge',options}}),verifyRegistration:async x=>{verified=x;return{data:{id:'registered'}}}}}};return {ctx,client,options,shown:()=>shown,verified:()=>verified}};
test('registration displays login ID without changing user handle or challenge',async()=>{const r=registrationContext({login_id:'driver_123',email:''});await r.ctx.SpodoraAccount.passkey(r.client,true);assert.equal(r.shown().user.name,'driver_123');assert.equal(r.shown().user.displayName,'driver_123');assert.deepEqual(Array.from(new Uint8Array(r.shown().user.id)),[3,4]);assert.deepEqual(Array.from(new Uint8Array(r.shown().challenge)),[1,2]);assert.equal(r.shown().rp.id,'spodora.com');assert.equal(r.verified().challengeId,'same-challenge');assert.equal(r.verified().credential.response.attestationObject,'Bwg');assert.equal(r.options.user.name,'random@accounts.spodora.invalid')});
test('legacy registration displays its actual email',async()=>{const r=registrationContext({login_id:null,email:'real@example.com'});await r.ctx.SpodoraAccount.passkey(r.client,true);assert.equal(r.shown().user.name,'real@example.com')});
test('failed label lookup never falls back to the internal address',async()=>{const r=registrationContext({error:'unauthorized'});await assert.rejects(r.ctx.SpodoraAccount.passkey(r.client,true),/設定できませんでした/);assert.equal(r.shown(),undefined)});
test('native JSON parsing and serialization remain supported',async()=>{let label;const r=registrationContext({login_id:'company_123',email:''});r.ctx.PublicKeyCredential.parseCreationOptionsFromJSON=x=>{label=x.user.name;return x};r.ctx.navigator.credentials.create=async()=>({toJSON:()=>({id:'native',type:'public-key'})});await r.ctx.SpodoraAccount.passkey(r.client,true);assert.equal(label,'company_123');assert.equal(r.verified().credential.id,'native')});
