const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=fs.existsSync(__dirname+'/driver.html')?__dirname:require('path').resolve(__dirname,'..'),token='11111111-1111-4111-8111-111111111111';
function ctx(rpc,user=true,workRows=[]){const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',className:'',disabled:false,hidden:false,append(){},querySelector(){return {}}});return elements.get(id)};const c={URL,URLSearchParams,location:{origin:'https://spodora.com',href:'https://spodora.com/attendance.html?company='+token},supabase:{createClient:()=>({rpc,auth:{getUser:async()=>({data:{user:user?{id:'test'}:null}})},from:table=>({select:()=>({eq:()=>table==='drivers'?{maybeSingle:async()=>({data:{id:1}})}:Promise.resolve({data:workRows})})})})},document:{hidden:false,getElementById:el,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},navigator:{},confirm:()=>true,console,setTimeout};c.addEventListener=()=>{};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(fs.existsSync(root+'/attendance-qr.js')?root+'/attendance-qr.js':root+'/assets/attendance-qr.js','utf8'),c);c.el=el;return c}
function inline(file){return [...fs.readFileSync(root+'/'+file,'utf8').matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(Boolean).join('\n')}
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
 for(const f of ['driver.html','company.html','company-workforce.html','index.html','company-attendance.html','company-attendance-qr.html','attendance.html','driver-attendance.html'])new vm.Script(f.endsWith('.js')?fs.readFileSync(root+'/'+f,'utf8'):inline(f),{filename:f});
 let c=ctx();assert.equal(c.SpodoraQR.token('https://spodora.com/attendance.html?company='+token),token);assert.equal(c.SpodoraQR.token('https://www.spodora.com/attendance.html?company='+token),token);assert.equal(c.SpodoraQR.token('https://evil.example/attendance.html?company='+token),'');assert.equal(c.SpodoraQR.token('DRIVERSPOT:'+token+':in'),'');assert.equal(c.SpodoraQR.token('https://spodora.com/attendance.html?company=bad'),'');
 let calls=[],stamp='2026-10-05T01:00:00Z';
 c=ctx(async(name,args)=>{calls.push({name,args});if(name==='company_scan_work')return{data:{company_name:'テスト企業',work:[{id:12,title:'<配送>',work_date:'2026-10-05',start_time:'09:00:00',end_time:'17:00:00'}]}};return {data:{message:args.p_action==='in'?'出勤を記録しました':'退勤を記録しました',checked_in_at:stamp,checked_out_at:args.p_action==='out'?stamp:null}}});
 vm.runInContext(inline('attendance.html'),c);await tick();assert.match(c.el('work').innerHTML,/&lt;配送&gt;/);assert.match(c.el('work').innerHTML,/punch\(12,'in'\)/);await c.punch(12,'in');assert.match(c.el('work').innerHTML,/出勤中/);assert.match(c.el('work').innerHTML,/punch\(12,'out'\)/);await c.punch(12,'out');assert.match(c.el('work').innerHTML,/退勤済み/);assert(!c.el('work').innerHTML.includes('onclick'));assert.equal(calls[1].args.p_application_id,12);
 c=ctx(async()=>({error:{message:'このQRは無効です'}}));vm.runInContext(inline('attendance.html'),c);await tick();assert.equal(c.el('msg').className,'error');assert.match(c.el('msg').textContent,/無効/);
 c=ctx(null,false);vm.runInContext(inline('attendance.html'),c);await tick();assert.match(c.el('msg').innerHTML,/driver.html\?attendance=/);
 c=ctx();let stops=0;c.Html5Qrcode=class{async start(){throw Error('denied')}async stop(){stops++}};vm.runInContext(inline('driver-attendance.html'),c);await tick();await c.startScan();assert.equal(c.el('start').disabled,false);assert.equal(c.el('msg').className,'error');await c.accept('https://evil.example/attendance.html?company='+token);assert(!c.location.href.endsWith('evil'));await c.accept('https://spodora.com/attendance.html?company='+token);assert.equal(c.location.href,'./attendance.html?company='+token);
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),base={id:1,status:'勤務確定',jobs:{work_date:today,status:'募集中'}};
 for(const [workRows,expected] of [[[],0],[[base],1],[[base,{...base,id:2}],0],[[{...base,checked_out_at:stamp}],0],[[{...base,jobs:{work_date:today,status:'キャンセル'}}],0],[[{...base,jobs:{work_date:'2000-01-01',status:'募集中'}}],0],[[{...base,checked_in_at:stamp,jobs:{work_date:'2000-01-01',status:'募集中'}}],1]]){
  let starts=0;c=ctx(null,true,workRows);c.Html5Qrcode=class{async start(){starts++}async stop(){}};vm.runInContext(inline('driver-attendance.html'),c);await tick();assert.equal(starts,expected,JSON.stringify(workRows));
 }
 c=ctx(async(name,args)=>{calls.push({name,args});return {data:{company_name:'テスト企業',token}}});calls=[];c.Blob=Blob;c.QRCode=class{static CorrectLevel={M:1};constructor(){}};c.document.createElement=tag=>tag==='canvas'?{getContext:()=>({fillRect(){},drawImage(){}}),toBlob:cb=>cb(new Blob(['test'],{type:'image/png'})),toDataURL:()=> 'data:image/png;base64,test'}:{click(){}};vm.runInContext(inline('company-attendance-qr.html'),c);await tick();assert.equal(c.el('company').textContent,'テスト企業');assert.equal(c.el('copy').disabled,false);assert.equal(calls[0].args.p_regenerate,false);await c.copyQR();assert.match(c.el('msg').textContent,/画像を保存/);await c.regenerate();assert.equal(calls[1].args.p_regenerate,true);assert.match(c.el('msg').textContent,/以前のQRは無効/);c.confirm=()=>false;await c.regenerate();assert.equal(calls.length,2);
 const driver=fs.readFileSync(root+'/driver.html','utf8');assert(!driver.includes('makeAttendanceQR'));assert(!driver.includes('prepare_driver_attendance'));assert.match(driver,/出退勤スキャン/);assert.match(driver,/if\(!currentUser\)return showLogin\(\);if\(resumeAttendance\(\)\)/);
 console.log('PASS: syntax, safe QR parsing, multiple-work action rendering, in/out completion, invalid QR, login return, denied camera retry, driver entry.');
})().catch(e=>{console.error(e);process.exitCode=1});
